load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

js_library(
    name = "ui",
    srcs = [
        "ProductCategoryRow.js",
        "ProductRow.js",
        "ProductTable.js",
        "SearchBar.js",
        "index.js",
    ],
    deps = [
        ":node_modules/@demo/products",
        ":node_modules/@types/react",
        ":node_modules/react",
    ],
)

js_library(
    name = "ui_tests",
    testonly = True,
    srcs = ["ProductRow.test.js"],
    deps = [
        ":node_modules/@jest/globals",
        ":node_modules/@types/react",
        ":node_modules/@types/react-dom",
        ":node_modules/react",
        ":node_modules/react-dom",
        ":ui",
    ],
)

npm_package(
    name = "pkg",
    srcs = [
        "package.json",
        ":ui",
    ],
    visibility = ["//:__pkg__"],
)
