load("@aspect_rules_jest//jest:defs.bzl", "jest_test")
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("//tools/ts:defs.bzl", "ts_project")

npm_link_all_packages(name = "node_modules")

ts_project(
    name = "products",
    srcs = [
        "filter.ts",
        "index.ts",
        "products.ts",
    ],
    declaration = True,
    isolated_typecheck = True,
    tsconfig = "//:tsconfig",
)

ts_project(
    name = "products_tests",
    testonly = True,
    srcs = ["filter.test.ts"],
    declaration = True,
    isolated_typecheck = True,
    tsconfig = "//:tsconfig",
    deps = [
        ":node_modules/@jest/globals",
        ":products",
    ],
)

npm_package(
    name = "pkg",
    srcs = [
        "package.json",
        ":products",
    ],
    visibility = ["//:__pkg__"],
)

jest_test(
    name = "test",
    data = [
        "package.json",
        ":products_tests",
    ],
    node_modules = "//:node_modules",
    node_options = ["--experimental-vm-modules"],
)
